### ISSUE TITLE
Livestream Checklist

### ISSUE THREAD

**Issue by ramblinjan** [ramblinjan/stator#1]
- [ ] Spin up demo page
  - [ ] Enable distributable build
  - [ ] Include library in page
- [ ] Add event hooks
  - [ ] Pushstate
  - [ ] Popstate
- [ ] Tie in to demo page
